# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
development:
  url: redis://localhost:6379/4

test:
  url: redis://localhost:6379/3

production: 
  url: redis://:action_cable@pub-redis-12030.us-east-1-3.7.ec2.redislabs.com:12030
